In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
data = load_iris()

In [ ]:
x=data.data
y=data.target

In [ ]:
from keras.models import Sequential

In [ ]:
from keras.layers import Dense

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le=LabelEncoder().fit_transform(y)

In [ ]:
le

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from tensorflow.keras.utils import to_categorical

In [ ]:
encoded_y = to_categorical(le)

In [ ]:
encoded_y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
model = Sequential()
model.add(Dense(10, input_dim=4, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,encoded_y,test_size=0.2)

In [ ]:
model.fit(xtrain, ytrain, epochs=100, batch_size=10)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.3180 - loss: 1.6731
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.2867 - loss: 1.5445 
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3187 - loss: 1.3174 
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.2670 - loss: 1.2972 
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.2709 - loss: 1.2200 
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.2689 - loss: 1.1788 
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3276 - loss: 1.1079 
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3109 - loss: 1.1027 
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3462 - loss: 1.0722 
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.2726 - loss: 1.0790  
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3412 - loss: 1.0367 
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 

In [ ]:
predictions = model.predict(xtest)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step


In [ ]:
for i in range(0,30,3):
  print(predictions[i],"                             ", ytest[i])


[9.9016660e-01 9.7236615e-03 1.0965706e-04]                               [1. 0. 0.]
[6.7086227e-04 3.2271463e-01 6.7661452e-01]                               [0. 0. 1.]
[0.00054699 0.5038764  0.49557665]                               [0. 0. 1.]
[0.0009485  0.36719722 0.63185424]                               [0. 0. 1.]
[1.70358064e-04 1.06524356e-01 8.93305242e-01]                               [0. 0. 1.]
[9.8845053e-01 1.1392782e-02 1.5666182e-04]                               [1. 0. 0.]
[7.4658665e-04 2.3228110e-01 7.6697230e-01]                               [0. 0. 1.]
[0.00127626 0.45083046 0.5478933 ]                               [0. 0. 1.]
[0.00329564 0.7119409  0.28476343]                               [0. 1. 0.]
[9.9391854e-01 6.0281302e-03 5.3343530e-05]                               [1. 0. 0.]


In [ ]:
predicted_classes = np.argmax(predictions, axis=1)

In [ ]:
for i in range(0,30,3):
  print(predicted_classes[i],"                             ", ytest[i])

0                               [1. 0. 0.]
2                               [0. 0. 1.]
1                               [0. 0. 1.]
2                               [0. 0. 1.]
2                               [0. 0. 1.]
0                               [1. 0. 0.]
2                               [0. 0. 1.]
2                               [0. 0. 1.]
1                               [0. 1. 0.]
0                               [1. 0. 0.]
